Cova/Cova/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include ('apps.main.urls', namespace="main")),
    url(r'^', include ('apps.users.urls', namespace="users")),
    url(r'^', include ('apps.message.urls', namespace="message")),
]

Cova/apps/main/urls.py
from django.conf.urls import url

from .views import Home


urlpatterns = [

    url(r'^$', Home.as_view(), name="home"),
    


]

Cova/apps/message/urls.py
from django.conf.urls import url

from .views import Email


urlpatterns = [

    url(r'^email/$',Email.as_view(), name="email"),
    


]

Cova/apps/users/urls.py
from django.conf.urls import url
from .views import LogInView, UserRegisterView
from . import views

urlpatterns = [
    url(r'^ingresar/$', LogInView.as_view(), name='login'),
    url(r'^salir/$', views.LogOut, name='logout'),
    url(r'^registrar/$', UserRegisterView.as_view(), name='register'),


]

Cova/apps/message/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

Cova/apps/users/models.py
# usuario/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models



class UserManager(BaseUserManager, models.Manager):

    def _create_user(self,username, email, password, is_staff,
                     is_superuser, **extra_fields):
        email=self.normalize_email(email)
        if not email:
            raise ValueError('El email debe ser obligatorio')
        user=self.model(username=username, email=email, is_active=True, is_staff=is_staff
                   ,**extra_fields )

        user.setpassword(password)
        user.save(using=self._db)
        return user

    def create_user(self,username,email,password=None,**extra_fields):
        return self._create_user(username,email,password, False,False,**extra_fields)

    def create_superuser(self,username,email,password=None,**extra_fields):
        return self._create_user(username,email,password, True,True,**extra_fields)

class User(AbstractUser):
    is_medical = models.BooleanField(default=False)    
    is_patient = models.BooleanField(default=False)
    num_cole=models.CharField(max_length=64, default=0)
    num_hist=models.CharField(max_length=64, default=0)

    class Meta:
        db_table = 'users_db'

class MedicalProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    name = models.CharField(max_length=64)
    num_coleg=models.CharField(max_length=64, default=0)


class PatientProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    name = models.CharField(max_length=64)
    num_history=models.CharField(max_length=64, default=0)

Cova/apps/message/forms.py
from django import forms


class EmailForm(forms.Form):

	subject =forms.CharField(max_length=100,widget=forms.TextInput(attrs={
							'type' : 'text',
							'placeholder' : 'Escribe aqui el asunto'
						}))
	message= forms.CharField(widget=forms.Textarea(attrs={
							'type' : 'text',
							'placeholder' : 'Contenido del mensaje'
						}))
	to = forms.CharField(max_length=50,
					widget=forms.TextInput(attrs={
							'type' : 'email',
							'placeholder' : 'Destinatario'
						}))
	sender= forms.EmailField(widget=forms.TextInput(attrs={
							'type' : 'email',
							'placeholder' : 'Emisor'
						}))

	

Cova/apps/users/forms.py
from django import forms
from .models import User, MedicalProfile

class UserLoginForm(forms.Form):

	username = forms.CharField(max_length=50,
					widget=forms.TextInput(attrs={
							'type' : 'text',
							'placeholder' : 'Ingresa un nombre de usuario'
						}))
	password = forms.CharField(max_length=50,
					widget=forms.TextInput(attrs={
							'type' : 'password',
							'placeholder' : 'Ingresa una password'
						}))

	def clean(self):
		user_exist = User.objects.filter(username = self.cleaned_data['username'])
		if not user_exist:
			self.add_error('username', 'El nombre de usuario no existe!')
		else:
			user = User.objects.get(username = self.cleaned_data['username'])
			if not user.check_password(self.cleaned_data['password']):
				self.add_error('password', 'El password es incorrecto')


class UserCreateForm(forms.ModelForm):

	class Meta:
		model= User
	
		fields=('username', 'first_name', 'last_name', 'email', 'password')
		widgets={
			'username':forms.TextInput(attrs={
				'type': 'text',
				'placeholder': 'Ingresa un nombre de usuario'
				}),
			'first_name':forms.TextInput(attrs={
				'type': 'text',
				'placeholder': 'Ingresa tu nombre'
				}),
			'last_name':forms.TextInput(attrs={
				'type': 'text',
				'placeholder': 'Ingresa tu apellido'
				}),
			'password':forms.TextInput(attrs={
				'type': 'password',
				'placeholder': 'Ingresa un password'
				}),
			'email':forms.TextInput(attrs={
				'type': 'email',
				'placeholder': 'Ingresa un a direccion de correo'
				}),
			'num_coleg':forms.TextInput(attrs={
				'type': 'text',
				'placeholder': 'Ingresa el numero del colegiado'
				}),
		}


 

Cova/apps/main/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .models_user import User
# Create your views here.


class Home(TemplateView):

	template_name = 'main/home.html'

	def get_context_data(self, **kwargs):
		context=super(Home, self).get_context_data(**kwargs)
		context['users'] = User.objects.all()
		context['medical'] = User.objects.filter(is_medical=True)
		context['patient'] = User.objects.filter(is_patient=True)
		
		return context
		

Cova/apps/message/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.http import *
from django.core.urlresolvers import reverse_lazy, reverse
from django.views.generic import TemplateView, FormView
from .forms import EmailForm
from .models_user import User
# Create your views here.


class Email(FormView):
	form_class = EmailForm
	template_name = 'message/email.html'
# Create your views here.
	
	success_url=reverse_lazy('main:home')

	def get_context_data(self, **kwargs):
		context=super(Email, self).get_context_data(**kwargs)
		context['users'] = User.objects.all()
		context['medical'] = User.objects.filter(is_medical=True)
		context['patient'] = User.objects.filter(is_patient=True)
		return context
		

	def form_valid(self, form):
		
		subject = form.cleaned_data['subject']
		message = form.cleaned_data['message']
		sender = form.cleaned_data['sender']
		cc_myself = form.cleaned_data['cc_myself']

		recipients = ['info@example.com']
		if cc_myself:
			recipients.append(sender)

		send_mail(subject, message, sender, recipients)
		

Cova/apps/users/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, FormView, CreateView
from django.core.urlresolvers import reverse_lazy, reverse
from django.contrib.auth import login, logout, authenticate

from .forms import UserLoginForm, UserCreateForm
# Create your views here.

def LogOut(request):
	logout(request)
	return redirect(reverse('main:home'))



class LogInView(FormView):

	template_name= 'users/login.html'
	form_class = UserLoginForm
	success_url=reverse_lazy('main:home')

	def form_valid(self, form):
		user = authenticate(
				username = form.cleaned_data['username'],
				password = form.cleaned_data['password']
					)
		if user.is_active:
			login(self.request, user)
			return super(LogInView, self).form_valid(form)
		else:
			return redirect(reverse('main:not_access'))




class UserRegisterView(CreateView):

	form_class = UserCreateForm
	template_name= 'users/register.html'
	success_url=reverse_lazy('users:login')

	def form_valid(self,form):
		user = form.save()
		user.set_password(form.cleaned_data['password'])
		return super(UserRegisterView,self).form_valid(form)

Cova/apps/main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title> C O V A </title>
	{% load static from staticfiles %}
	<link rel="stylesheet" href="{% static 'css/fonts.css' %}">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
</head>
<body>

	<header class="cabecera">
		<div class="container">		
			<div class="row row__space__between">
				<div class="logo"> <a href="{% url 'main:home' %}"> C O V A 	</a></div>	

				{% if not user.is_authenticated %}
			    <ul class="menu">
			    	<li class="menu__item"><a href="{% url 'users:login' %}">Login</a></li>
			      	<li class="menu__item"><a href="{% url 'users:register' %}">Registrarse</a></li>
			    </ul>
				{% else %}

			    <ul class="menu">
			    	<li class="menu__item_bienvenida"><a>Bienvenid@, {{user.username}}</a></li>
			      	<li class="menu__item"><a href="{% url 'users:logout' %}">Cerrar sesión</a></li>
			    </ul>

			    {% endif %}

			</div>
		</div>	
    </header>
<!-- 	<div class="container">
		<div class="row session">
			{% if user.is_authenticated %}
					<h4>Bienvenido, {{user.username}}</h4>
					<a class ="boton_salir" href="{% url 'users:logout' %}">Salir</a>
			{% endif %}
			{% if not user.is_authenticated %}
					<h4>Sesión no iniciada</h4>
					
			{% endif %}
		</div>
	</div> -->

    {% block content %}
    {% endblock content %}

   	<footer class="footer">
    	<div class="contenedor">
        	<hr class="footer__linea">
        	<span class="footer__texto"> Juan Yagüe Saldaña</span>
      	</div>
    </footer>

</body>
</html>

Cova/apps/main/templates/main/home.html
{% extends "base.html" %}

{% block content %}
	<section class="principal">
	{% if  user.is_authenticated %}
		<div class="contenedor">

			 <h1 class="principal__titulo">Correo electrónico </h1>
			<li class="menu__item"><a class="menu__item_correo_texto" href="{% url 'message:email' %}">Acceder</a></li>

 	</div>
 	{%endif%}
			<div class="libros">

<!-- 			
				{%for user in medical %}
					{{user.email}}
				{% endfor %} -->


		</div>
	</section>
{% endblock content %}

Cova/apps/main/templates/main/not_access.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	ACCESO DENEGADO
</body>
</html>

Cova/apps/message/templates/message/email.html
{% extends "base.html" %}

{% block content %}
	<div class="contenedor">

		<h2 class="formulario_correo">
			Envío de correo
		</h2>
		<section class="formulario_correo__datos">
			<form method="POST"> 
				{% csrf_token %}
				
				<select id="deslpegable_email" name="provincia">
				    <option value="" selected="selected">- Destinatario -</option>   
						{% if user.is_patient %}
						    {%for user in medical %}
						    	<option>{{user.email}}</option>
					    	{% endfor %}
			    		{% endif%}

						{% if user.is_medical %}
						    {%for user in patient %}
						    	<option>{{user.email}}</option>
					    	{% endfor %}
			    		{% endif%}
				    	
				    	

			    	 
					  
				
				</select>
 

				<div class="formulario_correo__datos__ingresar">
					
					{{ form.subject }}
					{{ form.subject.errors }}
				</div>
				<div class="formulario_correo__datos__ingresar">
					
					{{ form.message }}
					
				</div>
				


				<div class="formulario_correo__datos__ingresar">

					{{ form.sender }}
					
				</div>

				


				<button type="submit" class="login__registro__datos__boton">Enviar correo</button>
			</form>
		</section>

  	</div>


{% endblock content %}

Cova/apps/users/templates/users/login.html
{% extends "base.html" %}

{% block content %}
	<div class="contenedor">

		<h2 class="login__registro">
			Login
		</h2>
		<section class="login__registro__datos">
			<form method="POST">
				{% csrf_token %}
				<div class="login__registro__datos__ingresar">
				
					{{ form.username }}
					{{ form.username.errors }}
				</div>
				<div class="login__registro__datos__ingresar">
					
					{{ form.password }}
					{{ form.password.errors }}
				</div>
				<input type="submit" value="Ingresar" class="login__registro__datos__boton">
			</form>
		</section>
  	</div>
{% endblock content %}

Cova/apps/users/templates/users/register.html
{% extends "base.html" %}

{% block content %}
	<div class="contenedor">

		<h2 class="login__registro">
			Registro de usuarios
		</h2>
		<section class="login__registro__datos">
			<form method="POST"> 
				{% csrf_token %}
				<div class="login__registro__datos__ingresar">
					
					{{ form.username }}
					{{ form.username.errors }}
				</div>
				<div class="login__registro__datos__ingresar">
					
					{{ form.first_name }}
					{{ form.first_name.errors }}
				</div>
				<div class="login__registro__datos__ingresar">

					{{ form.last_name }}
					{{ form.last_name.errors }}
				</div>

				<div class="login__registro__datos__ingresar">

					{{ form.password }}
					{{ form.password.errors }}
				</div>

				<div class="login__registro__datos__ingresar">

					{{ form.email }}
					{{ form.email.errors }}
				</div>


				<button type="submit" class="login__registro__datos__boton">Registrarse</button>
			</form>
		</section>

  	</div>
{% endblock content %}